## Array fundamentals

In [2]:
import numpy as np
import matplotlib.pyplot as plt
print("numpy", np.__version__)

numpy 2.3.5


In [2]:
# a demonstration
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
# initialize an arry

a = np.array([1, 2, 3, 4, 5, 6])
a[0]

np.int64(1)

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a[:3]

array([1, 2, 3])

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[3:]
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a[1,3]

np.int64(8)

## Array attributes

In [19]:
# ndim, 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a.ndim
a.shape
len(a.shape) == a.ndim


True

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11, 12]])
a.size
import math
math.prod(a.shape)
a.size == math.prod(a.shape)

True

In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.dtype

dtype('int64')

## How to create a basic array

In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
# random create
np.empty(2)

array([1., 1.])

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
np.ones(2, dtype = np.int64)

array([1, 1])

## Adding, removing, and sorting elements

In [39]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([[1, 2], [2, 3]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [2, 3],
       [5, 6]])

## How do you know the shape and size of an array?

In [48]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.size
array_example.shape
array_example.ndim

3

## reshape an array

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
b = a.reshape(3, 2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [56]:
a = np.arange(6)
print(np.reshape(a, shape = (1, 6), order = 'c'))

[[0 1 2 3 4 5]]
