In [1]:
import numpy as np

N = 4
n_states = N * N
terminals = {(0, 0), (3, 3)}
gamma = 1.0
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
V = np.zeros((4, 4))

def step(r, c, dr, dc):
    new_r = r + dr
    new_c = c + dc

    # Pulling values that exceed the boundaries back to the boundary edge, 
    # this handles the actions that go beyond the boundaries.
    new_r = max(0, min(3, new_r))
    new_c = max(0, min(3, new_c))

    # The reward is always -1
    reward = -1

    return ((new_r, new_c), reward)
    
for iteration in range(100):

    for r in range(4):
        for c in range(4):

            #The start and end point detection. These two points act as the base condition for this recursion. 
            #Therefore, even if gamma is 1, there can still be accurate values.
            if (r, c) in terminals:
                    continue

            candidates = []
            for dr, dc in actions:
                (new_r, new_c), reward = step(r, c, dr, dc)
                
                #Bellman equation
                candidate = reward + gamma * (V[new_r, new_c])

                candidates.append(candidate)

            V[r, c] = max(candidates)

print(V)    

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [4]:
arrow = {(-1, 0): "↑", (1, 0): "↓", (0, -1): "←", (0, 1): "→"}

policy = [[""for _ in range(4)]for _ in range(4)]

for r in range(4):
    for c in range(4):

        # The first time I wrote, I forgot to use "continue", 
        #which resulted in not being able to print out "T" and 
        #it was overwritten by the subsequent loop.
        if (r, c) in terminals:
            policy[r][c] = "T"
            continue

        best_value = float('-inf')
        best_action = None

        for (dr, dc) in actions:
            (new_r, new_c), reward = step(r, c, dr, dc)
            candidate = reward + gamma * (V[new_r, new_c])

            if candidate > best_value:
                best_value = candidate
                best_action = (dr, dc)

        #list and dic both use the "[]" to access the value    
        policy[r][c] = arrow[best_action]
        
# "".join can change the connection forms of various string types such as list tuples.
for row in policy:
    print(" ".join(row))
        
        

T ← ← ↓
↑ ↑ ↑ ↓
↑ ↑ ↓ ↓
↑ → → T


In [3]:
print(step(2, 2, -1, 0))   
print(step(0, 0, -1, 0))  
print(step(3, 3, 0, 1))  

((1, 2), -1)
((0, 0), -1)
((3, 3), -1)


In [1]:
import gymnasium as gym
print(gym.__version__)

1.3.0


In [5]:
env = gym.make("CartPole-v1")

#print("action_space:", env.action_space)
#print("observation_space:", env.observation_space)

observation, info = env.reset(seed = 42)
print("state is", observation)
print("style is", type(observation))
print("shape is", observation.shape)
print("info is", info)

action = 1
next_observation, reward, terminated, truncated, info = env.step(action)

print("action", action)
print("new observation is", next_observation)
print("reward is", reward)
print("terminated", terminated)
print("truncated", truncated)

state is [ 0.0273956  -0.00611216  0.03585979  0.0197368 ]
style is <class 'numpy.ndarray'>
shape is (4,)
info is {}
action 1
new observation is [ 0.02727336  0.18847767  0.03625453 -0.26141977]
reward is 1.0
terminated False
truncated False


In [10]:
observation, info = env.reset(seed = 42)

total_reward = 0
steps = 0

while True:
    action = env.action_space.sample()

    next_observation, reward, terminated, truncated, info = env.step(action)
    total_reward += reward
    steps += 1

    if terminated or truncated:
        break

    observation = next_observation

print(f"This round lasted for {steps}, total_reward is {total_reward}")
    

This round lasted for 12, total_reward is 12.0


In [18]:
import numpy as np

episode_reward = []

for episode in range(20):

    # The first time I wrote it without including this, the reward remained at 0
    observation, info = env.reset()
    total_reward = 0
    steps = 0

    while True:
        
        action = env.action_space.sample()
        next_observation, reward, terminated, truncated, info = env.step(action)
        
        total_reward += reward
        steps += 1
        
        if terminated or truncated:
            break
            
        observation = next_observation
    # episode_reward = episode_reward.append(total_reward), This way of writing is incorrect.
    episode_reward.append(total_reward)

episode_reward = np.array(episode_reward)
print(f"20 episodes average reward is {episode_reward.mean():.1f}")
print(f"the standard of reward is {episode_reward.std():.1f}")
print(f"the max is {episode_reward.max()}")
print(f"the min is {episode_reward.min()}")
    

        

20 episodes average reward is 22.4
the standard of reward is 12.1
the max is 54.0
the min is 10.0
