In [1]:
import numpy as np

N = 4
n_states = N * N
terminals = {(0, 0), (3, 3)}
gamma = 1.0
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
V = np.zeros((4, 4))

def step(r, c, dr, dc):
    new_r = r + dr
    new_c = c + dc

    # Pulling values that exceed the boundaries back to the boundary edge, 
    # this handles the actions that go beyond the boundaries.
    new_r = max(0, min(3, new_r))
    new_c = max(0, min(3, new_c))

    # The reward is always -1
    reward = -1

    return ((new_r, new_c), reward)
    
for iteration in range(100):

    for r in range(4):
        for c in range(4):

            #The start and end point detection. These two points act as the base condition for this recursion. 
            #Therefore, even if gamma is 1, there can still be accurate values.
            if (r, c) in terminals:
                    continue

            candidates = []
            for dr, dc in actions:
                (new_r, new_c), reward = step(r, c, dr, dc)
                
                #Bellman equation
                candidate = reward + gamma * (V[new_r, new_c])

                candidates.append(candidate)

            V[r, c] = max(candidates)

print(V)    

[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


In [4]:
arrow = {(-1, 0): "↑", (1, 0): "↓", (0, -1): "←", (0, 1): "→"}

policy = [[""for _ in range(4)]for _ in range(4)]

for r in range(4):
    for c in range(4):

        # The first time I wrote, I forgot to use "continue", 
        #which resulted in not being able to print out "T" and 
        #it was overwritten by the subsequent loop.
        if (r, c) in terminals:
            policy[r][c] = "T"
            continue

        best_value = float('-inf')
        best_action = None

        for (dr, dc) in actions:
            (new_r, new_c), reward = step(r, c, dr, dc)
            candidate = reward + gamma * (V[new_r, new_c])

            if candidate > best_value:
                best_value = candidate
                best_action = (dr, dc)

        #list and dic both use the "[]" to access the value    
        policy[r][c] = arrow[best_action]
        
# "".join can change the connection forms of various string types such as list tuples.
for row in policy:
    print(" ".join(row))
        
        

T ← ← ↓
↑ ↑ ↑ ↓
↑ ↑ ↓ ↓
↑ → → T


In [3]:
print(step(2, 2, -1, 0))   
print(step(0, 0, -1, 0))  
print(step(3, 3, 0, 1))  

((1, 2), -1)
((0, 0), -1)
((3, 3), -1)
