# Stage 2: Deep Learning Foundations and DQN with PyTorch

## 1. PyTorch Tensor Foundations

In [1]:
import numpy as np
import torch

print("PyTorch version:", torch.__version__)
print("MPS available:", torch.backends.mps.is_available())

PyTorch version: 2.12.0
MPS available: True


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"ones tensor \n {x_ones} \n")
print(f"rand tensor \n {x_rand} \n")

ones tensor 
 tensor([[1, 1],
        [1, 1]]) 

rand tensor 
 tensor([[0.8634, 0.8476],
        [0.4076, 0.2974]]) 



In [8]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"rand tensor : \n {rand_tensor} \n")
print(f"ones tensor : \n {ones_tensor} \n")
print(f"zeros tensor: \n {zeros_tensor} \n")

rand tensor : 
 tensor([[0.2542, 0.1335, 0.4595],
        [0.6940, 0.8079, 0.7033]]) 

ones tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [9]:
tensor = torch.rand(3,4)
print(f"shape of tensor {tensor.shape}")
print(f"datatype of tensor {tensor.dtype}")
print(f"Device tensor is stored on {tensor.device}")

shape of tensor torch.Size([3, 4])
datatype of tensor torch.float32
Device tensor is stored on cpu


In [18]:
tensor = torch.rand(3,4)

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

print(f"Device tensor is stored on {tensor.device}")

Device tensor is stored on mps:0


In [25]:
tensor = torch.ones(4, 4)
print(f"first row: {tensor[0]}")
print(f"first column: {tensor[:, 0]}")
print(f"last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [27]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [28]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [32]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [35]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"f: {n}")

t: tensor([1., 1., 1., 1., 1.])
f: [1. 1. 1. 1. 1.]


In [36]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
np.add(n, 1, out = n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [46]:
import numpy as np
import torch

cartpole_state = np.array(
    [0.02, -0.01, 0.03, 0.04],
    dtype = np.float32
)

state_tensor = torch.tensor(cartpole_state)

print(f"shape: {state_tensor.shape}")

state_tensor = state_tensor.unsqueeze(0)

print("batch shape", state_tensor.shape)
print("dtype", state_tensor.dtype)

if torch.accelerator.is_available():
    state_tensor = state_tensor.to(
    torch.accelerator.current_accelerator()
    )

print("device", state_tensor.device)
print(state_tensor)


shape: torch.Size([4])
batch shape torch.Size([1, 4])
dtype torch.float32
device mps:0
tensor([[ 0.0200, -0.0100,  0.0300,  0.0400]], device='mps:0')


## 2. Neural Network Foundations: From Linear Models to PyTorch

### 2.1 Manual Forward Pass in PyTorch

In [47]:
import torch

x = torch.tensor([[2.0, 3.0]])
w = torch.tensor([
    [0.5],
    [1.0]
])
b = torch.tensor([[-2.0]])

z = x @ w + b
y_hat = torch.sigmoid(z)

print("x shape:", x.shape)
print("w shape:", w.shape)
print("z:", z)
print("predicted probability:", y_hat)

x shape: torch.Size([1, 2])
w shape: torch.Size([2, 1])
z: tensor([[2.]])
predicted probability: tensor([[0.8808]])


## 2.5 Batch Logistic Regression with Explicit Loops

In [52]:
import torch

# Three training examples, each with two features
X = torch.tensor([
    [1.0, 2.0],
    [2.0, 1.0],
    [-1.0, -2.0],
], dtype = torch.float32)

# Ground-truth labels
Y = torch.tensor([1.0, 1.0, 0.0], dtype = torch.float32)

# Model parameters
w = torch.tensor([0.0, 0.0], dtype = torch.float32)
b = torch.tensor(0.0, dtype = torch.float32)

# Accumulators
cost = torch.tensor(0.0)
dw = torch.zeros_like(w)
db = torch.tensor(0.0)

m = X.shape[0]

for i in range(m):
    x = X[i]
    y = Y[i]

    # Forward propagation
    z = torch.dot(x, w) + b
    a = torch.sigmoid(z)

    loss = -(y * torch.log(a) + (1 - y) * torch.log(1 - a))
    cost += loss

    # Manual backward propagation
    dz = a - y
    dw += x * dz
    db += dz


# Average over all training examples
cost /= m
dw /= m
db /= m

print("cost =", cost.item())
print("dw =", dw)
print("db =", db.item())

learning_rate = 0.1

w = w - learning_rate * dw
b = b - learning_rate * db

print("updated w =", w)
print("updated b =", b.item())   

cost = 0.6931471824645996
dw = tensor([-0.6667, -0.8333])
db = -0.1666666716337204
updated w = tensor([0.0667, 0.0833])
updated b = 0.01666666753590107
